// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Vscode = require("vscode");

function getFullTextRange($$document) {
  var firstLine = Curry._1($$document.lineAt, 0);
  var lastLine = Curry._1($$document.lineAt, $$document.lineCount - 1 | 0);
  return new Vscode.Range(0, firstLine.range.start.character, $$document.lineCount - 1 | 0, lastLine.range.end.character);
}

exports.getFullTextRange = getFullTextRange;
/* vscode Not a pure module */
