// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Node = require("./Node.bs.js");
var Vscode = require("./Vscode.bs.js");

var $$Error = $$Node.$$Error;

var Fs = $$Node.Fs;

var ChildProcess = $$Node.ChildProcess;

var Path = $$Node.Path;

var TextDocument = Vscode.TextDocument;

var Folder = Vscode.Folder;

var Workspace = Vscode.Workspace;

var $$Window = Vscode.$$Window;

var Commands = Vscode.Commands;

var ExtensionContext = Vscode.ExtensionContext;

exports.$$Error = $$Error;
exports.Fs = Fs;
exports.ChildProcess = ChildProcess;
exports.Path = Path;
exports.TextDocument = TextDocument;
exports.Folder = Folder;
exports.Workspace = Workspace;
exports.$$Window = $$Window;
exports.Commands = Commands;
exports.ExtensionContext = ExtensionContext;
/* Node Not a pure module */
