// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var TextDocument = { };

function key(f) {
  return f.uri.fsPath;
}

var Folder = {
  key: key
};

var Workspace = { };

var $$Window = { };

var Commands = { };

var ExtensionContext = { };

exports.TextDocument = TextDocument;
exports.Folder = Folder;
exports.Workspace = Workspace;
exports.$$Window = $$Window;
exports.Commands = Commands;
exports.ExtensionContext = ExtensionContext;
/* No side effect */
