// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var LSP = require("./LSP.bs.js");
var $$Node = require("./bindings/Node.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var VscodeLanguageclient = require("vscode-languageclient");

function createClient(id, name, folder) {
  return LSP.Server.make(folder.uri.fsPath).then((function (serverOptions) {
                return Promise.resolve(/* Ok */Block.__(0, [new VscodeLanguageclient.LanguageClient(id, name, serverOptions, LSP.Client.make(/* () */0))]));
              }));
}

function activate(context) {
  return LSP.MultiWorkspace.start(context, /* array */[], (function (_document, folder) {
                return createClient("merlin-language-server", "Merlin Language Server", folder).catch((function (e) {
                              var message = $$Node.$$Error.ofPromiseError(e);
                              return Promise.resolve(/* Error */Block.__(1, [message]));
                            }));
              }));
}

exports.activate = activate;
/* LSP Not a pure module */
