// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function $great$great$eq(o, f) {
  if (o !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(o));
  }
  
}

function $great$pipe(o, f) {
  if (o !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(o)));
  }
  
}

function $pipe$bang(o, f) {
  if (o !== undefined) {
    return /* () */0;
  } else {
    return Curry._1(f, /* () */0);
  }
}

exports.$great$great$eq = $great$great$eq;
exports.$great$pipe = $great$pipe;
exports.$pipe$bang = $pipe$bang;
/* No side effect */
